### PR TITLE
updated to use the latest bindings module

### PR DESCRIPTION
**Pull request by speier**
important to work with node 0.10.0

### CODE REVIEW

**Comment by speier** [comment]
great. could you please publish an updated npm package? thanks.

**Comment by lloyd** [comment]
give 0.2.3 a try?

**Comment by lloyd** [comment]
(now published)

**Comment by speier** [comment]
that was quick. :) it's working, thanks!
_tested with node 0.10.0 on windows_

**Comment by lloyd** [comment]
:high_brightness:

**Pull request merged**
